#!/bin/bash
set -euo pipefail
IFS=$'\n\t'


SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
source "${SCRIPT_DIR}"/env


main() {
    if [ ! -d "${BIN_DIR}" ]
    then
        mkdir "${BIN_DIR}"
    fi

    cat \
        <(echo -e '#!/bin/bash\n# !!! DO NOT EDIT THIS FILE !!!\n# !!! DO NOT EDIT THIS FILE !!!\n# !!! DO NOT EDIT THIS FILE !!!\n# It is machine generated.\n# If it needs editing, regenerate according to the readme.\n') \
        <(tail -n+2 "${SCRIPT_DIR}"/lit.sh) \
        > "${BIN_DIR}"/lit
    chmod +x "${BIN_DIR}"/lit
}


main
